# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e237b8d430d2846114df18de478e854c99b0968fb79be848cb9b0ccadb152497786c1de30a18a3f97cf9c0dd7cacf12d0051b75cc15585463210929b97ab618

test:
  secret_key_base: 7933d24b22a1895539bdefe659903006c8730d3541e6aec837af9a80114e8ee9236fa3c684d53be88a422a9e22f46c2b0516d8ceda730425843aac3443bcbf31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
